/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var e=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var s=Object.getOwnPropertyNames;var m=Object.prototype.hasOwnProperty;var h=(a,o)=>{for(var l in o)e(a,l,{get:o[l],enumerable:!0})},r=(a,o,l,c)=>{if(o&&typeof o=="object"||typeof o=="function")for(let d of s(o))!m.call(a,d)&&d!==l&&e(a,d,{get:()=>o[d],enumerable:!(c=t(o,d))||c.enumerable});return a};var u=a=>r(e({},"__esModule",{value:!0}),a);var b={};h(b,{default:()=>n});module.exports=u(b);var i=require("obsidian"),n=class extends i.Plugin{async onload(){this.addRibbonIcon("dice","Hello World",()=>{new i.Notice("Ciao dal tuo plugin!")}),this.addCommand({id:"hello-world-say-hello",name:"Di ciao",callback:()=>{new i.Notice("Ciao, mondo!")}})}onunload(){}};
